version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: assignment2_backend
    container_name: backend-container
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./secrets:/app/secrets:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: assignment2_frontend
    container_name: frontend-container
    ports:
      - "8501:8501"
    env_file:
      - ./.env
    depends_on:
      - backend
    volumes:
      - ./secrets:/app/secrets:ro

volumes:
  postgres_data:
