version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: your-backend-image
    container_name: backend-container
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./secrets:/run/secrets:ro
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
