[theme]
primaryColor="#4A90E2"  # A vibrant blue for primary actions
backgroundColor="#f5f7fa"  # Light grey for the main background
secondaryBackgroundColor="#e0e7ff"  # Soft lavender for secondary backgrounds
textColor="#333333"  # Dark grey for readability and contrast
font="sans serif"
